apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-fiar
  name: nodejs-svc
  namespace: node
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 3000
  selector:
    app: nodejs-fiar
